/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/detachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List detachments */
        get: operations["admin-list-detachments"];
        put?: never;
        /** Create a detachment */
        post: operations["admin-create-detachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/detachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a detachment */
        get: operations["admin-get-detachment"];
        /** Update a detachment */
        put: operations["admin-update-detachment"];
        post?: never;
        /** Delete a detachment */
        delete: operations["admin-delete-detachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all factions */
        get: operations["admin-list-factions"];
        put?: never;
        /** Create a faction */
        post: operations["admin-create-faction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/factions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a faction */
        get: operations["admin-get-faction"];
        /** Update a faction */
        put: operations["admin-update-faction"];
        post?: never;
        /** Delete a faction */
        delete: operations["admin-delete-faction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current admin info */
        get: operations["get-admin-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stratagems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stratagems */
        get: operations["admin-list-stratagems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployment-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deployment patterns */
        get: operations["list-deployment-patterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detachments/{detachmentId}/stratagems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stratagems for a detachment */
        get: operations["list-detachment-stratagems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all factions */
        get: operations["list-factions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factions/{factionId}/detachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List detachments for a faction */
        get: operations["list-detachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factions/{factionId}/stratagems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stratagems for a faction */
        get: operations["list-faction-stratagems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/force-dispositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List force dispositions */
        get: operations["list-force-dispositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's games */
        get: operations["list-games"];
        put?: never;
        /** Create a new game */
        post: operations["create-game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/join/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a game by invite code */
        post: operations["join-game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game state */
        get: operations["get-game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game event history */
        get: operations["get-game-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide a game from the current user's game list */
        post: operations["hide-game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mission-matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the disposition matchup matrix */
        get: operations["list-mission-matchups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List primary missions */
        get: operations["list-missions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secondary-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List secondary mission cards */
        get: operations["list-secondary-cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's completed game history */
        get: operations["get-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's game stats */
        get: operations["get-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminMeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AdminMeOutputBody.json
             */
            readonly $schema?: string;
            githubId: string;
            githubUser: string;
        };
        Award: {
            cumulative?: boolean;
            exclusive_group?: string;
            mode?: string;
            per?: string;
            /** Format: int64 */
            per_max?: number;
            trigger: components["schemas"]["Trigger"];
            /** Format: int64 */
            vp?: number;
            /** Format: int64 */
            vp_max?: number;
            /** Format: int64 */
            vp_per?: number;
            when?: components["schemas"]["Condition"];
        };
        Board: {
            deploymentPatternId: string;
            objectives: components["schemas"]["Objective"][] | null;
            playerSides: string[] | null;
        };
        Card: {
            awards: components["schemas"]["Award"][] | null;
            card_type: string;
            id: string;
            name: string;
            text: string;
        };
        Condition: {
            negated?: boolean;
            operands?: components["schemas"]["Condition"][] | null;
            operator?: string;
            parameters?: {
                [key: string]: unknown;
            };
            type?: string;
        };
        CreateGameOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateGameOutputBody.json
             */
            readonly $schema?: string;
            id: string;
            inviteCode: string;
        };
        DeploymentPattern: {
            description?: string;
            id?: string;
            name: string;
            /** @description Objective coordinates */
            objectives: unknown;
            recommendedTerrainLayoutIds: string[] | null;
            source?: string;
            territories: unknown;
            zones: unknown;
        };
        Detachment: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Detachment.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            detachmentPoints?: number;
            factionId: string;
            forceDispositions: string[] | null;
            id?: string;
            name: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Faction: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Faction.json
             */
            readonly $schema?: string;
            factionRuleId?: string;
            id?: string;
            name: string;
            parentFactionId?: string;
        };
        FactionStat: {
            factionName: string;
            /** Format: int64 */
            gamesPlayed: number;
            /** Format: int64 */
            wins: number;
        };
        ForceDisposition: {
            id?: string;
            name: string;
            text?: string;
        };
        GameEvent: {
            /** Format: date-time */
            createdAt: string;
            eventData: unknown;
            eventType: string;
            /** Format: int64 */
            id: number;
            phase: string | null;
            /** Format: int64 */
            playerNumber: number | null;
            /** Format: int64 */
            round: number | null;
        };
        GamePlayerSummary: {
            avatarUrl?: string;
            factionName?: string;
            /** Format: int64 */
            playerNumber: number;
            /** Format: int64 */
            totalVp: number;
            userId: string;
            username: string;
        };
        GameState: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GameState.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            abandonRequestedBy?: number;
            /** Format: int64 */
            activePlayer: number;
            board: components["schemas"]["Board"];
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            createdAt: string;
            currentPhase: string;
            /** Format: int64 */
            currentRound: number;
            /** Format: int64 */
            currentTurn: number;
            /** Format: int64 */
            firstTurnPlayer: number;
            gameId: string;
            inviteCode: string;
            players: components["schemas"]["PlayerState"][] | null;
            startOfTurnControl?: {
                [key: string]: number;
            };
            status: string;
            /** Format: int64 */
            vpPerGameCap: number;
            /** Format: int64 */
            vpPerRoundCap: number;
            winnerId?: string;
        };
        GameSummary: {
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            inviteCode: string;
            missionName?: string;
            players: components["schemas"]["GamePlayerSummary"][] | null;
            status: string;
            winnerId?: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
        };
        JoinGameOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/JoinGameOutputBody.json
             */
            readonly $schema?: string;
            id: string;
            inviteCode: string;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            avatar?: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            username: string;
        };
        Mission: {
            deploymentPatternIds: string[] | null;
            id?: string;
            name: string;
            /** Format: int64 */
            vpPerGameCap: number;
            /** Format: int64 */
            vpPerRoundCap: number;
        };
        MissionCard: {
            cardType: string;
            id?: string;
            name: string;
            subtype?: string;
            text?: string;
        };
        MissionMatchup: {
            disposition: string;
            id?: string;
            missionId: string;
            opponentDisposition: string;
        };
        Objective: {
            /** Format: int64 */
            controlledBy: number;
            homeSide?: string;
            /** Format: int64 */
            index: number;
            point: components["schemas"]["Point"];
            role: string;
            tags?: string[] | null;
            territorySide?: string;
        };
        PlayerState: {
            avatarUrl?: string;
            /** Format: int64 */
            cp: number;
            /** Format: int64 */
            cpGainedThisRound: number;
            detachments: components["schemas"]["SelectedDetachment"][] | null;
            factionId: string;
            factionName: string;
            fixedSecondaryIds: string[] | null;
            forceDisposition?: string;
            forceDispositionName?: string;
            missionId?: string;
            missionName?: string;
            pendingScorePrompts: components["schemas"]["ScorePrompt"][] | null;
            /** Format: int64 */
            playerNumber: number;
            primaryCard?: components["schemas"]["Card"];
            /** Format: int64 */
            primaryScoredThisRound: number;
            ready: boolean;
            secondaryDeck: components["schemas"]["SecondaryCard"][] | null;
            secondaryHand: components["schemas"]["SecondaryCard"][] | null;
            secondaryMode: string;
            secondaryScored: components["schemas"]["SecondaryCard"][] | null;
            /** Format: int64 */
            secondaryScoredThisRound: number;
            side?: string;
            stratagemsUsedThisPhase: string[] | null;
            userId: string;
            username: string;
            /** Format: int64 */
            vpPaint: number;
            /** Format: int64 */
            vpPrimary: number;
            /** Format: int64 */
            vpSecondary: number;
        };
        Point: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        RoundWindow: {
            /** Format: int64 */
            max?: number;
            /** Format: int64 */
            min?: number;
        };
        ScorePrompt: {
            /** Format: int64 */
            awardIndex: number;
            cardId: string;
            cardName: string;
            category: string;
            id: string;
            /** Format: int64 */
            round: number;
            text: string;
        };
        SecondaryCard: {
            awards: components["schemas"]["Award"][] | null;
            card_type: string;
            id: string;
            name: string;
            text: string;
            /** Format: int64 */
            vpScored?: number;
        };
        SelectedDetachment: {
            id: string;
            name: string;
            /** Format: int64 */
            points: number;
        };
        Stratagem: {
            category?: string;
            /** Format: int64 */
            cpCost: number;
            detachmentId?: string;
            factionId?: string;
            id?: string;
            name: string;
            phases: string[] | null;
            playerTurn?: string;
            timing?: string;
            type?: string;
        };
        Trigger: {
            battle_round?: components["schemas"]["RoundWindow"];
            phase?: string;
            player_turn?: string;
            timing?: string;
        };
        UserStats: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserStats.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            abandoned: number;
            /** Format: double */
            averageVp: number;
            /** Format: int64 */
            draws: number;
            factionStats: components["schemas"]["FactionStat"][] | null;
            /** Format: int64 */
            losses: number;
            /** Format: int64 */
            wins: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-list-detachments": {
        parameters: {
            query?: {
                /** @description Filter by faction ID */
                faction_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detachment"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-detachment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Detachment"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detachment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-get-detachment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detachment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-detachment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Detachment"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detachment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-detachment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-faction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Faction"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-get-faction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-faction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Faction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-faction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-admin-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-stratagems": {
        parameters: {
            query?: {
                /** @description Filter by faction ID */
                faction_id?: string;
                /** @description Filter by detachment ID */
                detachment_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stratagem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-deployment-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentPattern"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-detachment-stratagems": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Detachment ID */
                detachmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stratagem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-detachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Faction ID */
                factionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detachment"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-faction-stratagems": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Faction ID */
                factionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stratagem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-force-dispositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForceDisposition"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGameOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "join-game": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGameOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-game": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game ID */
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-game-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game ID */
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEvent"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "hide-game": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game ID */
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-mission-matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionMatchup"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-secondary-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionCard"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-history": {
        parameters: {
            query?: {
                /** @description Filter by player's faction name */
                myFaction?: string;
                /** @description Filter by opponent's faction name */
                opponentFaction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
